kind: ConfigMap
apiVersion: v1
metadata:
 name: backend
 namespace: expense
data:
 DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 namespace: expense
 labels:
   project: expense
   component: backend
   tier: app
spec:
 replicas: 2
 selector:
   matchLabels:
     project: expense
     component: backend
     tier: app
 template:
  metadata:
    labels:
      project: expense
      component: backend
      tier: app
  spec:
   containers:
   - name: backend
     image: joindevops/backend:v1.0
     envFrom:
     - configMapRef:
        name: backend

---
kind: Service
apiVersion: v1
metadata:
 name: backend
 namespace: expense
spec:
 selector:
   project: expense
   component: backend
   tier: app
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  



