apiVersion: v1
kind: Deployment
metadata:
 name: mysql
 namespace: expense
 labels:
   project: expense
   component: mysql
   tier: db
spec:
 replicas: 2
 selector:
   matchLabels:
     project: expense
     component: mysql
     tier: db
 template:
  metadata:
    labels:
      project: expense
      component: mysql
      tier: db
  spec:
    containers:
    - name: mysql
      image: joindevops/mysql:v1.0

---
kind: Service
apiVersion: v1
metadata:
 name: mysql
 namespace: expense
spec:
 selector:
   project: expense
   component: mysql
   tier: db
 ports:
 - protocol: TCP
   port: 3306
   targetPort: 3306
  



